stages:
  clean:
    cmd: python src/clean.py
    deps:
    - data/iris.csv
    - src/clean.py
    outs:
    - data/final_iris.csv
  data_split:
    cmd: python src/data_split.py
    deps:
    - data/final_iris.csv
    - src/data_split.py
    outs:
    - data/test_iris.csv
    - data/train_iris.csv
  train:
    cmd: python src/train.py
    deps:
    - data/test_iris.csv
    - data/train_iris.csv
    - src/train.py
    outs:
    - models/iris.joblib
